# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'central_widget.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CentralWidget(object):
    def setupUi(self, CentralWidget):
        CentralWidget.setObjectName("CentralWidget")
        CentralWidget.resize(1143, 526)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(CentralWidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.framePointWidget = QtWidgets.QFrame(CentralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framePointWidget.sizePolicy().hasHeightForWidth())
        self.framePointWidget.setSizePolicy(sizePolicy)
        self.framePointWidget.setMinimumSize(QtCore.QSize(350, 0))
        self.framePointWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.framePointWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.framePointWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.framePointWidget.setLineWidth(0)
        self.framePointWidget.setObjectName("framePointWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.framePointWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5.addWidget(self.framePointWidget)
        self.frameCenter = QtWidgets.QFrame(CentralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameCenter.sizePolicy().hasHeightForWidth())
        self.frameCenter.setSizePolicy(sizePolicy)
        self.frameCenter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameCenter.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameCenter.setObjectName("frameCenter")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frameCenter)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.graphicsView = CentralGraphicsView(self.frameCenter)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_4.addWidget(self.graphicsView)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 4, -1, -1)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonFolder = QtWidgets.QPushButton(self.frameCenter)
        self.pushButtonFolder.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/folder.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonFolder.setIcon(icon)
        self.pushButtonFolder.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonFolder.setObjectName("pushButtonFolder")
        self.horizontalLayout.addWidget(self.pushButtonFolder)
        self.label_3 = QtWidgets.QLabel(self.frameCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.labelWorkingDirectory = QtWidgets.QLabel(self.frameCenter)
        self.labelWorkingDirectory.setText("")
        self.labelWorkingDirectory.setObjectName("labelWorkingDirectory")
        self.horizontalLayout.addWidget(self.labelWorkingDirectory)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButtonZoomIn = QtWidgets.QPushButton(self.frameCenter)
        self.pushButtonZoomIn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/zoom_in.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonZoomIn.setIcon(icon1)
        self.pushButtonZoomIn.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonZoomIn.setObjectName("pushButtonZoomIn")
        self.horizontalLayout.addWidget(self.pushButtonZoomIn)
        self.pushButtonZoomOut = QtWidgets.QPushButton(self.frameCenter)
        self.pushButtonZoomOut.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/zoom_out.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonZoomOut.setIcon(icon2)
        self.pushButtonZoomOut.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonZoomOut.setObjectName("pushButtonZoomOut")
        self.horizontalLayout.addWidget(self.pushButtonZoomOut)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_5.addWidget(self.frameCenter)
        self.frameCustomField = QtWidgets.QFrame(CentralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameCustomField.sizePolicy().hasHeightForWidth())
        self.frameCustomField.setSizePolicy(sizePolicy)
        self.frameCustomField.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameCustomField.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameCustomField.setObjectName("frameCustomField")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frameCustomField)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBoxImageData = QtWidgets.QGroupBox(self.frameCustomField)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxImageData.sizePolicy().hasHeightForWidth())
        self.groupBoxImageData.setSizePolicy(sizePolicy)
        self.groupBoxImageData.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBoxImageData.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBoxImageData.setObjectName("groupBoxImageData")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBoxImageData)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBoxImageData)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEditX = QtWidgets.QLineEdit(self.groupBoxImageData)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditX.sizePolicy().hasHeightForWidth())
        self.lineEditX.setSizePolicy(sizePolicy)
        self.lineEditX.setObjectName("lineEditX")
        self.horizontalLayout_2.addWidget(self.lineEditX)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBoxImageData)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lineEditY = QtWidgets.QLineEdit(self.groupBoxImageData)
        self.lineEditY.setObjectName("lineEditY")
        self.horizontalLayout_3.addWidget(self.lineEditY)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.groupBoxCustomFields = QtWidgets.QGroupBox(self.groupBoxImageData)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxCustomFields.sizePolicy().hasHeightForWidth())
        self.groupBoxCustomFields.setSizePolicy(sizePolicy)
        self.groupBoxCustomFields.setObjectName("groupBoxCustomFields")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBoxCustomFields)
        self.verticalLayout_3.setContentsMargins(8, -1, 8, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_marking = QtWidgets.QLabel(self.groupBoxCustomFields)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_marking.sizePolicy().hasHeightForWidth())
        self.label_marking.setSizePolicy(sizePolicy)
        self.label_marking.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_marking.setObjectName("label_marking")
        self.horizontalLayout_4.addWidget(self.label_marking)
        self.lineEdit_marking = QtWidgets.QLineEdit(self.groupBoxCustomFields)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_marking.sizePolicy().hasHeightForWidth())
        self.lineEdit_marking.setSizePolicy(sizePolicy)
        self.lineEdit_marking.setObjectName("lineEdit_marking")
        self.horizontalLayout_4.addWidget(self.lineEdit_marking)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_manufacturer = QtWidgets.QLabel(self.groupBoxCustomFields)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_manufacturer.sizePolicy().hasHeightForWidth())
        self.label_manufacturer.setSizePolicy(sizePolicy)
        self.label_manufacturer.setObjectName("label_manufacturer")
        self.horizontalLayout_6.addWidget(self.label_manufacturer)
        self.lineEdit_manufacturer = QtWidgets.QLineEdit(self.groupBoxCustomFields)
        self.lineEdit_manufacturer.setObjectName("lineEdit_manufacturer")
        self.horizontalLayout_6.addWidget(self.lineEdit_manufacturer)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_partnumber = QtWidgets.QLabel(self.groupBoxCustomFields)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_partnumber.sizePolicy().hasHeightForWidth())
        self.label_partnumber.setSizePolicy(sizePolicy)
        self.label_partnumber.setObjectName("label_partnumber")
        self.horizontalLayout_7.addWidget(self.label_partnumber)
        self.lineEdit_partnumber = QtWidgets.QLineEdit(self.groupBoxCustomFields)
        self.lineEdit_partnumber.setObjectName("lineEdit_partnumber")
        self.horizontalLayout_7.addWidget(self.lineEdit_partnumber)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_package = QtWidgets.QLabel(self.groupBoxCustomFields)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_package.sizePolicy().hasHeightForWidth())
        self.label_package.setSizePolicy(sizePolicy)
        self.label_package.setObjectName("label_package")
        self.horizontalLayout_8.addWidget(self.label_package)
        self.lineEdit_package = QtWidgets.QLineEdit(self.groupBoxCustomFields)
        self.lineEdit_package.setObjectName("lineEdit_package")
        self.horizontalLayout_8.addWidget(self.lineEdit_package)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.groupBox = QtWidgets.QGroupBox(self.groupBoxCustomFields)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setTitle("")
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3.addWidget(self.groupBox)
        self.verticalLayout_2.addWidget(self.groupBoxCustomFields)
        self.groupBoxPosition = QtWidgets.QGroupBox(self.groupBoxImageData)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxPosition.sizePolicy().hasHeightForWidth())
        self.groupBoxPosition.setSizePolicy(sizePolicy)
        self.groupBoxPosition.setTitle("")
        self.groupBoxPosition.setObjectName("groupBoxPosition")
        self.posLabel = QtWidgets.QLabel(self.groupBoxPosition)
        self.posLabel.setGeometry(QtCore.QRect(2, -4, 91, 20))
        self.posLabel.setObjectName("posLabel")
        self.verticalLayout_2.addWidget(self.groupBoxPosition)
        self.verticalLayout_5.addWidget(self.groupBoxImageData)
        self.horizontalLayout_5.addWidget(self.frameCustomField)

        self.retranslateUi(CentralWidget)
        QtCore.QMetaObject.connectSlotsByName(CentralWidget)

    def retranslateUi(self, CentralWidget):
        _translate = QtCore.QCoreApplication.translate
        CentralWidget.setWindowTitle(_translate("CentralWidget", "Form"))
        self.pushButtonFolder.setToolTip(_translate("CentralWidget", "Load folder of images."))
        self.label_3.setText(_translate("CentralWidget", "Working Directory:"))
        self.pushButtonZoomIn.setToolTip(_translate("CentralWidget", "Zoom in."))
        self.pushButtonZoomOut.setToolTip(_translate("CentralWidget", "Zoom out."))
        self.groupBoxImageData.setTitle(_translate("CentralWidget", "PCB Data"))
        self.label.setText(_translate("CentralWidget", "Length"))
        self.label_2.setText(_translate("CentralWidget", "Width  "))
        self.groupBoxCustomFields.setTitle(_translate("CentralWidget", "Component details"))
        self.label_marking.setText(_translate("CentralWidget", "Marking"))
        self.label_manufacturer.setText(_translate("CentralWidget", "Manufacturer"))
        self.label_partnumber.setText(_translate("CentralWidget", "Partnumber"))
        self.label_package.setText(_translate("CentralWidget", "Package"))
        self.posLabel.setText(_translate("CentralWidget", "0,0"))

from ddg.central_graphics_view import CentralGraphicsView
