# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chip_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogChipExport(object):
    def setupUi(self, DialogChipExport):
        DialogChipExport.setObjectName("DialogChipExport")
        DialogChipExport.resize(327, 228)
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogChipExport)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(DialogChipExport)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.spinBoxWidth = QtWidgets.QSpinBox(self.groupBox)
        self.spinBoxWidth.setMinimum(1)
        self.spinBoxWidth.setMaximum(500)
        self.spinBoxWidth.setProperty("value", 200)
        self.spinBoxWidth.setObjectName("spinBoxWidth")
        self.horizontalLayout.addWidget(self.spinBoxWidth)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(54, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.spinBoxHeight = QtWidgets.QSpinBox(self.groupBox)
        self.spinBoxHeight.setMinimum(1)
        self.spinBoxHeight.setMaximum(500)
        self.spinBoxHeight.setProperty("value", 200)
        self.spinBoxHeight.setObjectName("spinBoxHeight")
        self.horizontalLayout.addWidget(self.spinBoxHeight)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(DialogChipExport)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButtonPng = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButtonPng.setChecked(True)
        self.radioButtonPng.setObjectName("radioButtonPng")
        self.horizontalLayout_3.addWidget(self.radioButtonPng)
        self.radioButtonJpeg = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButtonJpeg.setObjectName("radioButtonJpeg")
        self.horizontalLayout_3.addWidget(self.radioButtonJpeg)
        spacerItem1 = QtWidgets.QSpacerItem(151, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.line = QtWidgets.QFrame(DialogChipExport)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.progressBar = QtWidgets.QProgressBar(DialogChipExport)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonCancel = QtWidgets.QPushButton(DialogChipExport)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/cancel.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonCancel.setIcon(icon)
        self.pushButtonCancel.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout_2.addWidget(self.pushButtonCancel)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pushButtonExport = QtWidgets.QPushButton(DialogChipExport)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/export.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonExport.setIcon(icon1)
        self.pushButtonExport.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonExport.setObjectName("pushButtonExport")
        self.horizontalLayout_2.addWidget(self.pushButtonExport)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(DialogChipExport)
        QtCore.QMetaObject.connectSlotsByName(DialogChipExport)

    def retranslateUi(self, DialogChipExport):
        _translate = QtCore.QCoreApplication.translate
        DialogChipExport.setWindowTitle(_translate("DialogChipExport", "Dialog"))
        self.groupBox.setTitle(_translate("DialogChipExport", "Chip Size"))
        self.label.setText(_translate("DialogChipExport", "Width"))
        self.label_2.setText(_translate("DialogChipExport", "Height"))
        self.groupBox_2.setTitle(_translate("DialogChipExport", "Format"))
        self.radioButtonPng.setText(_translate("DialogChipExport", "png"))
        self.radioButtonJpeg.setText(_translate("DialogChipExport", "jpeg"))
        self.pushButtonCancel.setText(_translate("DialogChipExport", "Cancel"))
        self.pushButtonExport.setText(_translate("DialogChipExport", "Export"))

