# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ddg\ui\ecu_input_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ECUInputDialog(object):
    def setupUi(self, ECUInputDialog):
        ECUInputDialog.setObjectName("ECUInputDialog")
        ECUInputDialog.resize(327, 167)
        self.verticalLayout = QtWidgets.QVBoxLayout(ECUInputDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(ECUInputDialog)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ecu_comboBox = QtWidgets.QComboBox(self.groupBox)
        self.ecu_comboBox.setEditable(True)
        self.ecu_comboBox.setObjectName("ecu_comboBox")
        self.horizontalLayout.addWidget(self.ecu_comboBox)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(ECUInputDialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pcb_comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.pcb_comboBox.setEditable(True)
        self.pcb_comboBox.setObjectName("pcb_comboBox")
        self.horizontalLayout_3.addWidget(self.pcb_comboBox)
        self.pos_comboBox = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pos_comboBox.sizePolicy().hasHeightForWidth())
        self.pos_comboBox.setSizePolicy(sizePolicy)
        self.pos_comboBox.setObjectName("pos_comboBox")
        self.pos_comboBox.addItem("")
        self.pos_comboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.pos_comboBox)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.line = QtWidgets.QFrame(ECUInputDialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonCancel = QtWidgets.QPushButton(ECUInputDialog)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/cancel.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonCancel.setIcon(icon)
        self.pushButtonCancel.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout_2.addWidget(self.pushButtonCancel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButtonOk = QtWidgets.QPushButton(ECUInputDialog)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/export.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonOk.setIcon(icon1)
        self.pushButtonOk.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonOk.setObjectName("pushButtonOk")
        self.horizontalLayout_2.addWidget(self.pushButtonOk)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(ECUInputDialog)
        QtCore.QMetaObject.connectSlotsByName(ECUInputDialog)

    def retranslateUi(self, ECUInputDialog):
        _translate = QtCore.QCoreApplication.translate
        ECUInputDialog.setWindowTitle(_translate("ECUInputDialog", "Rename/Move Component"))
        self.groupBox.setTitle(_translate("ECUInputDialog", "ECU Name"))
        self.groupBox_2.setTitle(_translate("ECUInputDialog", "PCB Name"))
        self.pos_comboBox.setCurrentText(_translate("ECUInputDialog", "Top"))
        self.pos_comboBox.setItemText(0, _translate("ECUInputDialog", "Top"))
        self.pos_comboBox.setItemText(1, _translate("ECUInputDialog", "Bottom"))
        self.pushButtonCancel.setText(_translate("ECUInputDialog", "Cancel"))
        self.pushButtonOk.setText(_translate("ECUInputDialog", "OK"))
